### ISSUE TITLE
Publishing ROS output?

### ISSUE THREAD

**Issue by fairf4x** [JakobEngel/dso_ros#10]
I was able to compile and run dso_ros (catkin branch) on ROS kinetic. However I noticed that its only output is through `PangolinDSOViewer`. I would like to use DSO SLAM on a quadrotor equipped with a camera. My main motivation is to have some information about odometry based on camera video stream. It would be also great if I could use the output of DSO SLAM to build map of the environment.
Is it possible to publish `geometry_msgs/PoseStamped` and `sensor_msgs/PointCloud2` from dso_ros?

Ok. I just read the documentation more carefully and find the note about writing custom `Output3DWrapper`.

**Comment by JakobEngel** [comment]
I havn't implemented a ROS "standard" output wrapper - If you have a nice ROS-based output wrapper that works e.g. with rviz feel free to pull request it here, and I'll add it to the repo :)
