### ISSUE TITLE
catkin: missing catkin_package before build

### ISSUE THREAD

**Issue by JanQuenzel** [JakobEngel/dso_ros#4]
Hi, 
for the catkin-version to correctly rosrun the package after building, the CMakelists.txt misses: 

catkin_package(
  INCLUDE_DIRS 
  LIBRARIES DSO_LIBRARY
  CATKIN_DEPENDS geometry_msgs roscpp sensor_msgs cv_bridge
)

Greeetings, Jan

**Comment by JakobEngel** [comment]
thx! can you create a pull request for that change?
