### ISSUE TITLE
benchmarkSpecialOption was not declared 

### ISSUE THREAD

**Issue by chiragmajithia** [JakobEngel/dso_ros#6]
Hello,
I changed the CMakeLists.txt  file as suggested in #4  and I tried to compile the code, I get following error.
I am attaching the CMakeLists.txt file, for the reference.. 
`/home/chirag/vision/SLAM/src/dso_ros/src/main.cpp: In function ‘void parseArgument(char*)’:
/home/chirag/vision/SLAM/src/dso_ros/src/main.cpp:84:3: error: ‘benchmarkSpecialOption’ was not declared in this scope
   benchmarkSpecialOption = option;
`

[CMakeLists.txt](https://github.com/JakobEngel/dso_ros/files/601520/CMakeLists.txt)

**Comment by jingedawang** [comment]
I have the same problem with you.

**Comment by JakobEngel** [comment]
fixed, hopefully - I should refrain from committing stuff before properly testing it, my apologies!
